services:
  spark-master:
    image: apache/spark:3.5.7-java17-r
    container_name: spark-master
    command: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master" ]
    ports:
      - "38080:8080"
      - "37077:7077"


  spark-worker:
    image: apache/spark:3.5.7-java17-r
    container_name: spark-worker
    depends_on:
      - spark-master
    command: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077" ]
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    ports:
      - "8081:8081"
